### ISSUE TITLE
text when highlighting a comment is not properly visible/discernable

### ISSUE THREAD

**Issue by iamharpar** [codeSTACKr/codestackr-vscode-theme#1]
![Screenshot (3)](https://user-images.githubusercontent.com/37501628/93156993-ea4db300-f726-11ea-8e54-34212e42c463.png)

In the above screenshot when a comment is selected as you can see the comment text is not readable

**Comment by iamharpar** [comment]
Maybe ![#577997](https://placehold.it/15/577997/000000?text=+) will be a better option for comment foreground . 

![Screenshot (8)](https://user-images.githubusercontent.com/37501628/93157805-93e17400-f728-11ea-91e6-435ef6622579.png)


maybe if you approve then I can send a PR

**Comment by max-programming** [comment]
I was about to make an issue on this thing but it already existed lol

**Comment by codeSTACKr** [comment]
Yes, please submit a PR and I will approve. Thank you for your help!
